services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: se-app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: se-db
    container_name: db
    restart: always
    # environment:
      # MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
